# Generated by Django 2.1.7 on 2019-02-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('descri', models.CharField(max_length=220)),
                ('imag', models.ImageField(upload_to='')),
            ],
        ),
    ]
